# Generated by Django 5.2.7 on 2025-10-29 20:08

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('imagen_asistencia', models.ImageField(upload_to=app.models.ruta_guardado_asistencia)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
